### ISSUE TITLE
Can't install release (0.6.1) / nightly release to a specific namespace

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#930]
# Expected behavior
Can install nightly release into any namespace 

# Actual behavior
I cant install to namespace default 

# Steps to reproduce the problem

1. Try to install nightly release into default namespace
2.
3.

# Environment (e.g. Docker Desktop, OpenShift)

# Tekton Pipelines version (e.g. 0.9.2, 0.8.0, master)
Nightly 

# Tekton Triggers version (e.g. 0.2, 0.1, master)

# Tekton Dashboard version (e.g. 0.4.0, 0.3.0, master)

# Additional Info
```
clusterrole.rbac.authorization.k8s.io/tekton-dashboard-minimal configured
clusterrolebinding.rbac.authorization.k8s.io/tekton-dashboard-minimal unchanged
the namespace from the provided object "tekton-pipelines" does not match the namespace "default". You must pass '--namespace=tekton-pipelines' to perform this operation.
the namespace from the provided object "tekton-pipelines" does not match the namespace "default". You must pass '--namespace=tekton-pipelines' to perform this operation.
the namespace from the provided object "tekton-pipelines" does not match the namespace "default". You must pass '--namespace=tekton-pipelines' to perform this operation.
the namespace from the provided object "tekton-pipelines" does not match the namespace "default". You must pass '--namespace=tekton-pipelines' to perform this operation.
the namespace from the provided object "tekton-pipelines" does not match the namespace "default". You must pass '--namespace=tekton-pipelines' to perform this operation.
```

**Comment by AlanGreene** [comment]
@CarolynMabbott is this resolved by https://github.com/tektoncd/dashboard/pull/1262#issuecomment-616409266 ?

**Comment by CarolynMabbott** [comment]
Im not sure if it is because to get the dashboard to install in a different namespace I had to manually edit the `namespace:tekton-pipelines` to default to install and check that it still worked to detect versions 

I have the latest code and when I try and install to a different namespace by adding `-n default` on the end I still get a similar but slightly shorter error 
```
Carolyns-MacBook-Pro:dashboard carolynmabbott$  kustomize build overlays/dev | ko apply -f - -n default 
2020/04/21 09:22:53 Using base gcr.io/distroless/base:nonroot for github.com/tektoncd/dashboard/cmd/dashboard
2020/04/21 09:22:54 Building github.com/tektoncd/dashboard/cmd/dashboard
2020/04/21 09:23:00 Publishing docker.io/carolyn92/dashboard-9623576a202fe86c8b7d1bc489905f86:latest
2020/04/21 09:23:24 Published docker.io/carolyn92/dashboard-9623576a202fe86c8b7d1bc489905f86@sha256:b8a993d9a5dbfc528e022830d7eef02f11195c8455b54f54ac7d4444722d9a06
customresourcedefinition.apiextensions.k8s.io/extensions.dashboard.tekton.dev unchanged
clusterrole.rbac.authorization.k8s.io/tekton-dashboard-minimal unchanged
clusterrolebinding.rbac.authorization.k8s.io/tekton-dashboard-minimal unchanged
the namespace from the provided object "tekton-pipelines" does not match the namespace "default". You must pass '--namespace=tekton-pipelines' to perform this operation.
the namespace from the provided object "tekton-pipelines" does not match the namespace "default". You must pass '--namespace=tekton-pipelines' to perform this operation.
the namespace from the provided object "tekton-pipelines" does not match the namespace "default". You must pass '--namespace=tekton-pipelines' to perform this operation.
2020/04/21 09:23:24 error executing 'kubectl apply': exit status 1
```

**Comment by 2020testuser** [comment]
@AlanGreene Is this issue resolved? I'm running into the same issue. Tried installing different versions of the Dashboard by passing the namespace (used only by non-admin user) and no luck. More details on this issue would be very helpful and I will close my other issue if duplicate.

**Comment by AlanGreene** [comment]
@2020testuser sorry this one slipped through the cracks. Did you resolve your issue?

Closing this as we haven't had other reports, and we've since updated a number of aspects of our config and install story.

If you're still seeing issues let us know (probably best to open a new issue) and we can take a look.
